{
 "title": "Kandula App Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Per Second (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(opsschool_monitor_views_count{method=\"view_home\"}[1m])"
    },
    {
     "expr": "rate(opsschool_monitor_views_count{method=\"view_scheduler\"}[1m])"
    },
    {
     "expr": "rate(opsschool_monitor_views_count{method=\"view_metrics\"}[1m])"
    },
    {
     "expr": "rate(opsschool_monitor_views_count{method=\"view_about\"}[1m])"
    },
    {
     "expr": "rate(opsschool_monitor_views_count{method=\"view_health\"}[1m])"
    },
    {
     "expr": "rate(opsschool_monitor_views_count{method=\"view_instances\"}[1m])"
    }
   ]
  },
  {
   "title": "Total Requests Per Minute",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(opsschool_monitor_views_count{job=\"kandula\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Page View Chart",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opsschool_monitor_views_count{method=\"view_home\"}"
    },
    {
     "expr": "opsschool_monitor_views_count{method=\"view_scheduler\"}"
    },
    {
     "expr": "opsschool_monitor_views_count{method=\"view_metrics\"}"
    },
    {
     "expr": "opsschool_monitor_views_count{method=\"view_about\"}"
    },
    {
     "expr": "opsschool_monitor_views_count{method=\"view_health\"}"
    },
    {
     "expr": "opsschool_monitor_views_count{method=\"view_instances\"}"
    }
   ]
  },
  {
   "title": "Avg. Response Time (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(opsschool_monitor_views_sum{method=\"view_home\"}[1m])"
    },
    {
     "expr": "increase(opsschool_monitor_views_sum{method=\"view_scheduler\"}[1m])"
    },
    {
     "expr": "increase(opsschool_monitor_views_sum{method=\"view_metrics\"}[1m])"
    },
    {
     "expr": "increase(opsschool_monitor_views_sum{method=\"view_about\"}[1m])"
    },
    {
     "expr": "increase(opsschool_monitor_views_sum{method=\"view_health\"}[1m])"
    },
    {
     "expr": "increase(opsschool_monitor_views_sum{method=\"view_instances\"}[1m])"
    }
   ]
  },
  {
   "title": "Total Page View Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opsschool_monitor_views_count{method=\"view_home\"}"
    },
    {
     "expr": "opsschool_monitor_views_count{method=\"view_scheduler\"}"
    },
    {
     "expr": "opsschool_monitor_views_count{method=\"view_metrics\"}"
    },
    {
     "expr": "opsschool_monitor_views_count{method=\"view_about\"}"
    },
    {
     "expr": "opsschool_monitor_views_count{method=\"view_health\"}"
    },
    {
     "expr": "opsschool_monitor_views_count{method=\"view_instances\"}"
    }
   ]
  }
 ]
}